// Generated by https://quicktype.io
export interface PathsResponse {
  currency: string
  deals: Deal[]
}
export interface Deal {
  transport: Transport
  departure: string
  arrival: string
  duration: Duration
  cost: number
  discount: number
  reference: string
}
export interface Duration {
  h: string
  m: string
}
export enum Transport {
  Bus = 'bus',
  Car = 'car',
  Train = 'train',
}
